name: teraaformworkflowtest
on:
    push:
        branches:
            - main

jobs:
    builds:
        runs-on: "ubuntu-latest"
        defaults:
            run:
                working-directory: "04-Terraform" 
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3.1.1

            - name: "List directories"
              run: ls

            - name: "Terraform FMT"
              id: fmt
              run: terraform fmt
              continue-on-error: true