name: myfirstworkflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: failurestep
        run: | 
          echo "I will fail"
          exit 0

  second_job:
    runs-on: ubuntu-latest
    steps:  
      - name: step2
        run: echo "Hello second Job today"

