name: myfirstworkflow
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: failurestep
        run: | 
          echo "I will fail"
          exit 0

  second_job:
    runs-on: windows-latest
    steps:  
      - name: step2
        shell: bash
        run: echo "Ths runner is $RUNNER_OS"

