name: myfirstworkflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello first job today"

  second_job:
    runs-on: ubuntu-latest
    steps:  
      - name: step2
        run: echo "Hello second Job today"

